config/routes.rb
Rails.application.routes.draw do
  root to: "payments#index"
  resources :payments, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  require "active_merchant/billing/rails"

  attr_accessor :card_security_code
  attr_accessor :credit_card_number
  attr_accessor :expiration_month
  attr_accessor :expiration_year

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :card_security_code, presence: true
  validates :credit_card_number, presence: true
  validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :expiration_year, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  validate :valid_card

  def credit_card
    ActiveMerchant::Billing::CreditCard.new(
      number:              credit_card_number,
      verification_value:  card_security_code,
      month:               expiration_month,
      year:                expiration_year,
      first_name:          first_name,
      last_name:           last_name
    )
  end

  def valid_card
    if !credit_card.valid?
      errors.add(:base, "The credit card information you provided is not valid.  Please double check the information you provided and then try again.")
      false
    else
      true
    end
  end

  def process
    if valid_card
      response = GATEWAY.authorize(amount * 100, credit_card)
      if response.success?
        transaction = GATEWAY.capture(amount * 100, response.authorization)
        if !transaction.success?
          errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
          false
        end
        update_columns({authorization_code: transaction.authorization, success: true})
        true
      else
        errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
        false
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      if @payment.process
        redirect_to payments_path, notice: "The user has been successfully charged." and return
      end
    end
    render 'new'
  end

  private

  def payment_params
    params.require(:payment).permit(:first_name, :last_name, :credit_card_number, :expiration_month, :expiration_year, :card_security_code, :amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def months
    (1..12).collect{|n| ["#{n} - #{Date::MONTHNAMES[n]}", n]}
  end

  def years
    (Time.now.year..Time.now.year+15)
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentCardApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<h1>Payment Attempts</h1>
<div class="well">
<%= link_to "New Payment", new_payment_path, class: "btn btn-primary" %>
</div>
<% if !flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-bordered table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Last 4</th>
    <th>Amount</th>
    <th>Succeeded?</th>
    <th>Authorization Code</th>
  </tr>
  <% if @payments.size > 0 %>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.first_name %></td>
        <td><%= payment.last_name %></td>
        <td><%= payment.last4 %></td>
        <td><%= number_to_currency payment.amount %></td>
        <td><%= payment.success == true ? "Yes" : "No" %></td>
        <td><%= payment.authorization_code %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="5">No payments have been attempted.</td>
    </tr>
  <% end %>
</table>

app/views/payments/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>New Payment</h1>

    <% if @payment.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @payment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="well">
      <%= form_for @payment do |f| %>
        <div class="form-group">
          <%= f.label :first_name, class: "control-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, class: "control-label" %>
          <%= f.text_field :last_name,class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :credit_card_number, class: "control-label" %>
          <%= f.text_field :credit_card_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_month, class: "control-label" %>
          <%= f.select :expiration_month, months, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_year, class: "control-label" %>
          <%= f.select :expiration_year, years, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :card_security_code, class: "control-label" %>
          <%= f.text_field :card_security_code, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :amount, class: "control-label" %>
          <%= f.number_field :amount, class: "form-control", step: "0.01" %>
        </div>
        <div class="form-group">
          <%= f.submit "Charge Credit Card", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>